# Generated by Django 2.2 on 2019-04-02 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
